project:
  title: "minimal-quarto-resume"
  render:
    - minimal_quarto_resume.qmd
execute:
  echo: FALSE
  output: asis
format: minimal-quarto-resume-typst 
keep_typ: true
style:
  font-header: "Roboto"
  font-text: "Source Sans Pro"
  color-accent: "DC143C"